apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ai-research-ppt
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30080
      protocol: TCP
  type: NodePort
